In [10]:
import numpy as np
x, y = np.mgrid[0:5, 2:8]
print(x)
print("------------------")
print(y)
print(np.c_[x.ravel(), y.ravel()].shape)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]]
------------------
[[2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]
 [2 3 4 5 6 7]]
(30, 2)


In [2]:
from scipy.spatial import KDTree
# ravel() 類似 flatten()，壓成1d array
# np.c_ 將兩個1d array合併成一個2d array e.g. [1,2,3], [4,5,6]=> [1, 4],
#                                                               [2, 5],
#                                                               [3, 6]
tree = KDTree(np.c_[x.ravel(), y.ravel()])   
# 查詢兩個點
dd, ii = tree.query([[0, 0], [2.2, 2.9]], k=1)
print(dd, ii, sep='-\n')
# 查詢最近的兩個點
# k: 最近的k個點, workers:用全部cpu
dd, ii = tree.query([[0, 0], [2.2, 2.9]], k=2, workers=-1)
print(dd, ii, sep='\n')

[2.        0.2236068]
[ 0 13]
[[2.         2.23606798]
 [0.2236068  0.80622577]]
[[ 0  6]
 [13 19]]


In [16]:
np.c_[x.ravel(), y.ravel()]

array([[0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [0, 6],
       [0, 7],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6],
       [1, 7],
       [2, 2],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [2, 7],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 5],
       [3, 6],
       [3, 7],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 6],
       [4, 7]])

In [14]:
from annoy import AnnoyIndex
import random

f = 40  # f維空間、被索引的向量長度

t = AnnoyIndex(f, 'angular') # AnnoyIndex(f, metric)  metric: "angular", "euclidean", "manhattan", "hamming", or "dot"
for i in range(1000):
    v = [random.gauss(0, 1) for z in range(f)] #v: (40,1)
    t.add_item(i, v) # i: >0， 第i個元素, v:向量

t.build(10, n_jobs=-1) #  build(n_trees, n_jobs=-1) 建立n_trees的forest
t.save('test.ann')

True

In [18]:
len(v)

40

In [13]:
%pip install annoy

  Using cached annoy-1.17.0-cp39-cp39-win_amd64.whl
